name: aeson-compat
version: 1.0.0.0
maintainer: Freckle Education
category: Utils
github: freckle/aeson-compat
synopsis: Compatibility modules between major aeson versions
description: |
  TODO

extra-doc-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-safe
  - -Wno-unsafe

  # Not all branches use all imports
  - -Wno-unused-imports

when:
  - condition: "impl(ghc >= 9.2)"
    ghc-options:
      - -Wno-missing-kind-signatures
  - condition: "impl(ghc >= 8.10)"
    ghc-options:
      - -Wno-missing-safe-haskell-mode
      - -Wno-prepositive-qualified-module

      # Not all branches use all deps
      - -Wno-unused-packages
  - condition: "impl(ghc >= 8.8)"
    ghc-options:
      - -fwrite-ide-info

dependencies:
  - base < 5

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - hashable
    - text
    - text-short
    - these
    - unordered-containers

tests:
  # spec:
  #   main: Spec.hs
  #   source-dirs: tests
  #   ghc-options: -threaded -rtsopts "-with-rtsopts=-N"
  #   dependencies:
  #     - aeson-compat
  #     - hspec
  #     - hspec-junit-formatter

  readme:
    main: README.lhs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - aeson
      - aeson-compat
      - markdown-unlit
